Add functionality for access Details URL endpoint
ZaraTech/UrlShortener pull request #4
Opened 2016-11-22 20:22 UTC by aitorsanz

2016-11-22 21:24 UTC, juan-vg commented
Resolve the conflicts, please.

2016-11-22 21:24 UTC, juan-vg requested changes
Resolve the conflicts, please.

2016-11-22 21:24 UTC, juan-vg commented on team/src/main/webapp/WEB-INF/jsp/details.jsp
> +<%@ page language="java" %>
I think you should remove these lines

2016-11-22 21:33 UTC, aitorsanz commented
Ok

El 22 nov. 2016 10:24 p. m., "Juan Vela" <notifications@github.com>
escribió:

> *@juan-vg* requested changes on this pull request.
>
> Resolve the conflicts, please.
> ------------------------------
>
> In team/src/main/webapp/WEB-INF/jsp/details.jsp
> <https://github.com/ZaraTech/UrlShortener/pull/4#pullrequestreview-9760840>
> :
>
> > @@ -1,14 +1,18 @@
> +<%@ page language="java" %>
>
> I think you should remove these lines
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ZaraTech/UrlShortener/pull/4#pullrequestreview-9760840>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKsQnNqkTNawJJ_webxo0FKT0cX6CEUHks5rA12fgaJpZM4K55l5>
> .
>

2016-11-23 14:09 UTC, juan-vg approved these changes

2016-11-23 14:09 UTC, merged